version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    command: python -m flask run --host=0.0.0.0 --port=8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
volumes:
  mongo-data:
